### ISSUE TITLE
disableFriendlyErrors not exposed

### ISSUE THREAD

**Issue by mattt-b** [p5-types/p5.ts#11]
https://github.com/processing/p5.js/wiki/Optimizing-p5.js-Code-for-Performance#disable-the-friendly-error-system-fes

`Property 'disableFriedlyErrors' does not exist`

**Comment by Zalastax** [comment]
Unfortunately, [disableFriendlyErrors does not seem to have YUIDocs](https://github.com/processing/p5.js/blob/95ca847962f416ce951da5fc171d2258633e9cd7/src/core/main.js#L585), which we require for generating the definitions. The best way to fix this is to open a PR for p5.js, adding YUIDoc for it, as in [this property](https://github.com/processing/p5.js/blob/0a458330a86cde0886d89c6ea6fbfaa0b4b74bc4/src/core/environment.js#L85).

I believe you'll want something like:
```JS
/**
 * @property {Boolean} disableFriendlyErrors
 */
p5.disableFriendlyErrors = false;
```

Feel free to ask more questions here but I'll close the issue since we shouldn't fix it in this repo.
