### ISSUE TITLE
p5/lib/p5.dom.min not found on request

### ISSUE THREAD

**Issue by mictadlo** [p5-types/p5.ts#2]
Hi,
I got `p5/lib/p5.dom.min not found on request` while using the following code:

`src/sketch.ts` 
```
import 'p5';
import "p5/lib/p5.dom.min";
```
The `package.json` looks like this:
```
    {
    	"dependencies": {
    		"p5": "^0.6.1"
    	},
    	"devDependencies": {
    		"@types/node": "^10.3.1",
    		"fuse-box": "^3.2.2",
    		"tslib": "^1.9.2",
    		"typescript": "^2.9.1",
    	}
    }
```
fuse.js:
```
const {FuseBox, WebIndexPlugin} = require('fuse-box');

const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js',
  sourceMaps: true,
  globals: { "p5": "p5" },
  plugins: [
      WebIndexPlugin(),
  ]
});

fuse.dev({open : true});

fuse.bundle('app')
  .instructions('> sketch.ts +p5')
  .hmr({reload: true})
  .watch()

fuse.run();
```
It seems the . in p5.dom.min  is the [problem](https://github.com/fuse-box/fuse-box/issues/1290#issuecomment-396134278) 

Thank you in advance.

Michal

**Comment by Zalastax** [comment]
I've made an [Example](https://github.com/p5-types/p5.ts/tree/c29b4390f7221fd1acd744d2335d7520aea80014/examples/webpack-global) that imports the minified files using webpack. You can also try the [augmentation style](https://github.com/p5-types/p5.ts/blob/c29b4390f7221fd1acd744d2335d7520aea80014/DefinitelyTyped/types/p5/test-augmentation/index.ts).
From the issue you linked it seems like FuseBox can't handle dots? Do they support [aliases](https://webpack.js.org/configuration/resolve/#resolve-alias) so that you can give `p5.dom` a name without dots?

**Comment by mictadlo** [comment]
Could you please contact FuseBox team and ask the question because I do not know?

Thank you in advance.

Michal

**Comment by Zalastax** [comment]
No, sorry, I don't have any affiliations with FuseBox.
Your code example works with webpack so I'd recommend using that instead.

**Comment by mictadlo** [comment]
Could you please post the webpack project here?

Thank you in advance.

Michal

**Comment by Zalastax** [comment]
Look in the examples directory :smiley:
There's one for p5 in instance mode and one for global mode.
