### ISSUE TITLE
Guide to contributing

### ISSUE THREAD

**Issue by kyeshmz** [p5-types/p5.ts#34]
Hi, 
Been using types with JS as multiple people working  on the same project  without types is often crazy.
I wanted to contribute to some of the types, most notably the createButton types.
I tried  
```
git clone https://github.com/p5-types/p5.ts
yarn
yarn run 

gyp ERR! node -v v15.9.0
gyp ERR! node-gyp -v v4.0.0
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/ssh2.a] Error 1

```
Is there a version that I need to be running  for node  or other  pre dependencies?
Thanks in advance

**Comment by Zalastax** [comment]
Hi, I'm not sure but there might be version incompatibilities. I am running on Windows and these are my versions:
```
p5.ts> npm -v
6.4.1
p5.ts> node -v
v8.12.0
```

As pointed out in #12, `nodegit` is causing issues for some. I had hopes of automating generation of new types but I never got to it. The version of p5.ts is quite tied to p5.js and will continue to be, so my hopes are not achievable anyways.

But enough about that. Have you tried the commands in the README?
```
yarn
yarn run download-p5
yarn run generate-data
yarn run generate
```

**Comment by kyeshmz** [comment]
So it seems that there are some dependency issues with a more recent version of node, I tried node 10 and it doesn't work as well.
Is it safe to say that the nodegit module is used to build some of the documentation?

The current repo right now is really hard to just add some type definitions, though I think I am doing the same thing that fal works is doing here #31

**Comment by kyeshmz** [comment]
In any case, I am also willing to create some kind of CI ( probably github actions in this case) for testing out the build and stuff!

**Comment by Zalastax** [comment]
nodegit is used to pull p5.js and checkout different versions. P5.js is compiled via generate-data. The generated data is used as input for creating the typings.

The reason it is hard to add some type definitions is because this project doesn't own the types, it just translates the types from the YUIDoc of p5.js. l don't intend to change that.

CI is welcome, but it'll look very red. I'm not actively maintaining.

Removing nodegit as suggested in #12 would be very good. That work is just deleting code and adding documentation for grabbing the data.json.
